### ISSUE TITLE
No possibility of viewing the state of the book + doesn't seem to consume orders

### ISSUE THREAD

**Issue by SimonOuellette35** [gavincyi/LightMatchingEngine#11]
See attached code. I wrote some simple code that displays the prices and quantities currently available on the book. When I submit a new order that should consume the other side (I buy 500 at the price of the ask), it doesn't seem to do so, although the resulting trade execution is properly recorded. That is, when I view the book after that, I still have 1500 offered on the ask, even though in theory I should have only 1000 left.

[testBook.TXT](https://github.com/gavincyi/LightMatchingEngine/files/3935242/testBook.TXT)

**Comment by gavincyi** [comment]
The order object follow the FIX protocol. It means the quantity is static while the attribute `leaves_qty` shows the unmatched quantity.

Followed with your example, if you look up the best offer order, the leaves qty is 500 rather than 1000. It shows the 500 quantity has been consumed.
```
In [16]: lob.order_books['ABC'].asks[10.09][0].leaves_qty
Out[16]: 500.0

In [17]: lob.order_books['ABC'].asks[10.09][0].qty
Out[17]: 1000.0

```
