### ISSUE TITLE
Any material on simulating the order matching

### ISSUE THREAD

**Issue by AaronX121** [gavincyi/LightMatchingEngine#12]
Hi, thanks for sharing this cool Repo, I found it quite useful in practice.

I would like to ask that whether there is any good material on introducing the order matching algorithms publicly available? I find details lying behind a matching engine quite complex, and I want to have a better understanding on order matching to facilitate my research.

Looking forward to your reply, thanks !

**Comment by gavincyi** [comment]
Normally the exchanges describe the matching algorithm and the expected behavior on adding / canceling / amending the orders. For example you can refer to the CME one https://www.cmegroup.com/confluence/plugins/servlet/mobile?contentId=101286568#content/view/101286568

**Comment by AaronX121** [comment]
Thanks, I will take a look.
