### ISSUE TITLE
Bid orders with leaves_qty < 1e-09 not removed from book, results in unexpected behavior

### ISSUE THREAD

**Issue by dikkechill** [gavincyi/LightMatchingEngine#13]
In some unexpected cases LightMatchingEngine gives the following error:
```
"Match quantity must be larger than zero"
```
The problem occurs sometimes due to float arithmetic with small quantities.
Because of this the leaves_qty of an order can become smaller than the 1e-9 threshold.
As the checking code in lightmatchingengine.pyx is different for bids than for asks, trying to clear the order with a leaves_qty < 1e-9 is impossible.

To fix this, the leaves_qty and match_qty bid side code in lightmatchingengine.pyx should be made consistent with the ask side code.
```
110    assert match_qty > 0, "Match quantity must be larger than zero"
```
Should become
```
110    assert match_qty >= 1e-9, "Match quantity must be larger than zero"
```
And
```
144    if order.leaves_qty > 0.0:
````
Should become
```
144    if order.leaves_qty >= 1e-9:
 ```

**Comment by gavincyi** [comment]
Thanks for your contribution and it's a nice catch!
