### ISSUE TITLE
 how to settle accounts for buyers and sellers after matchmaking

### ISSUE THREAD

**Issue by kenneth** [gavincyi/LightMatchingEngine#2]
Why is there no user ID, how to settle accounts for buyers and sellers after matchmaking?

**Comment by gavincyi** [comment]
May I know what your use case is?

**Comment by kenneth** [comment]
crypto exchange for example。
1.new order
2.match trade
3.settlement

so not just match trade, we need know which user id then i can settlement

**Comment by gavincyi** [comment]
This can be traced from the order id.
