### ISSUE TITLE
[Question] How to persist the Orderbook state between the API requests?

### ISSUE THREAD

**Issue by tomekit** [gavincyi/LightMatchingEngine#9]
Totally new to Python, but having read the code I've got the impression it's just the simple matching engine which can be run by long-running process which keeps the order book in-memory and reads the orders from the queue. Is there any way to persist its state in-memory between subsequent API requests? Thanks

**Comment by gavincyi** [comment]
What state would you like preserve? The whole order book or only the best prices?

**Comment by tomekit** [comment]
Given that there might be a request with "big order" coming in I would probably need to keep the whole order book or at least part of it, so the matching engine can fulfil the order. The "big order" might match with potentially many existing orders.

**Comment by gavincyi** [comment]
Yes the client should keep the state of the whole order book while the server should return only the changes, and snapshot if necessary. Sorry that I still cannot get why it is required? Could you please elaborate a bit more of your use case and your expected functionality?

**Comment by tomekit** [comment]
Hi @gavincyi, 
Yes the server should return only the changes and snapshot to the client. However server itself needs to keep the whole state, so it can match order requests coming from client.

My questions is actually where the server keeps that data between subsequent requests.
Does it use external DB or keeps in memory? If it keeps in memory can you please point me to place in the code which does it? 
I am trying to work out what's the mechanism to preserve the orderbook state (on the server side) between the subsequent. Thanks !
